name: HealthBar
authors: [filoghost,electronrussia]
main: com.gmail.filoghost.healthbar.Main
version: ${project.version}
website: http://dev.bukkit.org/bukkit-plugins/health-bar/

commands:
   healthbar:
      description: Main command for HealthBar, use /hbr help for commands.
      usage: /<command>
      aliases: [hbr,hbar]
